name: philippines_loan
description: 菲律宾第二套

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_easyloading: ^3.0.3
  permission_handler: ^8.2.6
  flutter_easyrefresh: ^2.2.1
  appsflyer_sdk: ^6.4.0+1
  flutter_facebook_sdk: ^1.0.0
  fluttercontactpicker: ^4.5.1
  contacts_service: ^0.6.3
  crypto: ^3.0.1
  device_info_plus: ^3.1.0
  memory_info: ^0.0.2
  device_information: ^0.0.4
  battery: ^2.0.3
  flutter_screenutil: ^5.0.0+2
  dio: ^4.0.1
  package_info_plus: ^1.3.0
  uuid: 3.0.5
  shared_preferences: ^2.0.8
  url_launcher: ^6.0.12
  sprintf: ^6.0.0
  fluttertoast: ^8.0.8
  liveness_plugin:
    path: liveness_plugin
  app_info:
    path: app_info
flutter_intl:
  enabled: true
flutter:
  uses-material-design: true
  assets:
    - assets/images/img_welcome.png
    - assets/images/img_btn_ok.png
    - assets/images/img_ben_cancel.png
    - assets/images/img_bg.png
    - assets/images/icon_not_select.png
    - assets/images/img_slide_red.png
    - assets/images/img_slide_gray.png
    - assets/images/icon_selected.png
    - assets/images/icon_down.png
    - assets/images/img_btn_bg.png
    - assets/images/img_rd_bg.png
    - assets/images/icon_up.png
    - assets/images/icon_tab_pay.png
    - assets/images/img_line.png
    - assets/images/icon_ip_n.png
    - assets/images/icon_down_r.png
    - assets/images/img_user_info.png
    - assets/images/img_usercontact.png
    - assets/images/img_card_bank.png
    - assets/images/img_work_info.png
    - assets/images/img_user_icon.png
    - assets/images/icon_my_loan.png
    - assets/images/icon_my_bg.png
    - assets/images/icon_my_user_call.png
    - assets/images/icon_my_about.png
    - assets/images/icon_my_exit.png
    - assets/images/icon_my_coupon.png
    - assets/images/icon_tab_pay_n.png
    - assets/images/icon_pop_close.png
    - assets/images/icon_my_user_info.png
 - assets/images/icon_main_user_n.png
 - assets/images/icon_main_user_y.png